### ISSUE TITLE
IPolicyEvaluator.AuthorizeAsync Returns Wording is Not Clear

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/ApiDocs#38]
On the [IPolicyEvaluator.AuthorizeAsync Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.policy.ipolicyevaluator.authorizeasync?view=aspnetcore-2.0) page, the `Returns` message states the following:

>Returns Success() if authorization succeeds. Otherwise returns Forbid() if Succeeded, otherwise returns Challenge()

The part that is confusing to me is:

> Otherewise returns Forbid() if Succeeded

Maybe it should be

>Otherwise returns Forbid() if Failed

I'm not sure what the author was trying to say.  I'm happy to submit a PR if someone could clarify what the intent was 😄

**Comment by spottedmahn** [comment]
@scottaddie

**Comment by spottedmahn** [comment]
Hi @HaoK - I just realized the comments are [coming from the code](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs#LC64).  Can you clarify your comments here?  Thanks!

**Comment by HaoK** [comment]
Yeah its a bit confusing...  So basically its doing the following:

If authorization succeeds, `AuthorizationPolicyResult.Success` is returned.
Otherwise: it returns `Forbid` if the `AuthenticateResult.Succeeded`, otherwise it will return `Challenge`.

Basically if authZ fails, it returns forbid if authN was successful, otherwise it will return challenge.

**Comment by spottedmahn** [comment]
I think I get it now.  If the **policy** fails (therefore I don't have access) and If I have been **authenticated** return `Forbid` otherwise return `Challenge` as I haven't been authenticated.

----

After reviewing [the code](https://github.com/aspnet/Security/blob/644f34e90d35b369efdce9c11ab1db42e0a7f4a7/src/Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs) I noticed there are 2 types involved here, not one. 

FYI, when you read the docs on the website it omits stuff I see in the code summary that I think helps clarify to the reader.

![image](https://user-images.githubusercontent.com/14079228/31908901-6160b73e-b806-11e7-9afc-8e71d0032963.png)

vs

![image](https://user-images.githubusercontent.com/14079228/31908943-89e14dd6-b806-11e7-838b-9b7645ca830e.png)
