### ISSUE TITLE
IHostedService should be available for 2.2

### ISSUE THREAD

**Issue by JohnCOsborne** [aspnet/ApiDocs#94]
Currently you get redirected to 2.1 when trying to view the API docs for IHostedService in 2.2

**Comment by scottaddie** [comment]
We're still working through some build warnings for the 2.2 API pages and hope to have them published within the next week. Thank you for your patience.

**Comment by bitbonk** [comment]
There are a lot of other `Microsoft.Extension.*` APIs that are not available for 2.2  (e.g. [ServiceCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.iservicecollection?view=aspnetcore-2.2), [ServiceCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollection?view=aspnetcore-2.2), [IHostLifetime](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostlifetime?view=aspnetcore-2.2), [IOption<TOption>](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.options.ioptions-1?view=aspnetcore-2.2))

**Comment by RoidingwANN** [comment]
Microsoft.Extension.* APIs seem to be a ongoing issue?

**Comment by scottaddie** [comment]
The ASP.NET Core 2.2 APIs have been published. For example, see https://docs.microsoft.com/dotnet/api/?view=aspnetcore-2.2&term=IHostedService.
